### ISSUE TITLE
Duplicated rules about create* and get* methods in factories

### ISSUE THREAD

**Issue by RodinVasily** [spryker/architecture-sniffer#27]
It seems like we have 2 checks for `create*` methods, which have similar functionality:
```
\ArchitectureSniffer\Common\Factory\FactoryCreateContainOneNewRule
\ArchitectureSniffer\Zed\Persistence\Factory\ZedPersistenceFactoryCreateContainOneNewRule
```
Second one is not used in any *.xml files and also has not sufficient logic. 
Should we remove it?

The same issue with `get*` methods:
```
\ArchitectureSniffer\Common\Factory\FactoryGetContainNoNewRule
\ArchitectureSniffer\Zed\Persistence\Factory\ZedPersistenceFactoryGetContainNoNewRule
```
however here both are used.. is that any difference?

**Comment by dereuromark** [comment]
Yes, we should remove one here.
Also please check if the other factories also are duplicate or if everything else is fine.

**Comment by RodinVasily** [comment]
I've found one more duplicated rule, however it seems to be not so trivial. Let's continue discussion in PR!
