### ISSUE TITLE
FacadeReturnValueRule is not working when using {@inheritdoc}

### ISSUE THREAD

**Issue by RodinVasily** [spryker/architecture-sniffer#34]
The rule, which says
```
Every Facade should only return native types or transfer objects.
```
is very easy to deceive (even not intentionally). I usually write Facades using `{@inheritdoc}` comment (because all annotations already defined in FacadeInterface) and in this case this rule is not working.

Possible solutions:
1) Deny `{@inheritdoc}` in Facades
2) Scan interfaces
3) Make smart mechanism of parsing Facade first and then Interface

**Comment by dereuromark** [comment]
You are using inheritdoc then wrong
We only use `{@inheritdoc}` not `@inheritdoc`. The latter is allowed to completely replace doc block, the first must keep all @ rows.
So in that case there is no issue.

**Comment by RodinVasily** [comment]
Ok, thanks for tip, I didn't know about such difference. But do we have a rule to deny using `@inheritdoc` in Facades? I haven't met it before.

**Comment by dereuromark** [comment]
Well, we dont use it for the reasons above, but there is no sniffer to check for it yet.
