### ISSUE TITLE
getBridgedInterfaceReflection return value NULL is not accepted by findNotMatchingMethodsForBridgeInterface

### ISSUE THREAD

**Issue by kfrohwein** [spryker/architecture-sniffer#78]
https://github.com/spryker/architecture-sniffer/blob/db5f56a25e9903c0409fd3053e8e4bda4af91977/src/Common/Bridge/BridgeMethodsRule.php#L233

I try to update our packages and you did add the bridge check in 0.4.1

If I am correct ->getBridgedInterfaceReflection() is checking the __construct of the bridge. If none is found it returns NULL as stated in the methods return types.

But this is used in ->findNotMatchingMethodsForBridgeInterface() which only accepts 

https://github.com/spryker/architecture-sniffer/blob/db5f56a25e9903c0409fd3053e8e4bda4af91977/src/Common/Bridge/BridgeMethodsRule.php#L177

I would say it is correct that  ->getBridgedInterfaceReflection() can return NULL if there is no constructor for some reason. So findNotMatchingMethodsForBridgeInterface should be changed.

For now I will downgrade the package again to 0.4.0

**Comment by tvaleriy** [comment]
Hi @kfrohwein, sorry for the late notification here. It's not forgotten or something. An internal ticket is waiting to be taken into development. I'll notify here once it's fixed.

Best,
Spryker Support Team

**Comment by dereuromark** [comment]
In what case do you not have an interface here? On project level implementation if you don't want to use interface contracting?

**Comment by dereuromark** [comment]
This will be resolved with https://github.com/spryker/architecture-sniffer/pull/80

Bridges are core-only constructs and must not be used on project level. As such an interface is always required as per our guidelines on this architecture topic.
