### ISSUE TITLE
False positive: AllMethodsPublicInFacadeRule in AbstractFacade

### ISSUE THREAD

**Issue by dereuromark** [spryker/architecture-sniffer#92]
Methods on abstract class are not relevant for the sniff.
We can check if they need to be public, though.

- AllMethodsPublicInFacadeRule
  * [Spryker.Kernel] Zed Business Layer - Facade: The method "Spryker\Zed\Kernel\Business\AbstractFacade::getFactory()" is not public which violates rule "A facade must only contain public methods."
    (src/Spryker/Zed/Kernel/Business/AbstractFacade.php)
  * [Spryker.Kernel] Zed Business Layer - Facade: The method "Spryker\Zed\Kernel\Business\AbstractFacade::resolveFactory()" is not public which violates rule "A facade must only contain public methods."
    (src/Spryker/Zed/Kernel/Business/AbstractFacade.php)
  * [Spryker.Kernel] Zed Business Layer - Facade: The method "Spryker\Zed\Kernel\Business\AbstractFacade::getFactoryResolver()" is not public which violates rule "A facade must only contain public methods."
    (src/Spryker/Zed/Kernel/Business/AbstractFacade.php)

**Comment by dereuromark** [comment]
Also

  * [Spryker.Url] Zed Business Layer - Facade: The method "Spryker\Zed\Url\Business\UrlFacade::legacyCreateUrl()" is not public which violates rule "A facade must only contain public methods."
    (src/Spryker/Zed/Url/Business/UrlFacade.php)
  * [Spryker.Url] Zed Business Layer - Facade: The method "Spryker\Zed\Url\Business\UrlFacade::legacyHasUrl()" is not public which violates rule "A facade must only contain public methods."
    (src/Spryker/Zed/Url/Business/UrlFacade.php)
  * [Spryker.Url] Zed Business Layer - Facade: The method "Spryker\Zed\Url\Business\UrlFacade::legacyDeleteUrlRedirect()" is not public which violates rule "A facade must only contain public methods."
    (src/Spryker/Zed/Url/Business/UrlFacade.php)
    
Deprecated methods should also be excluded as here it is already part of deprecation legacy cleanup requirement

**Comment by dereuromark** [comment]
Can we close this @dmytro-dymarchuk

**Comment by dmytro-dymarchuk** [comment]
> Can we close this @dmytro-dymarchuk

I think yes
